mensa/django-mensa/app/urls.py
# app/urls.py
from django.urls import path, include
from . import views


app_name = 'app'

urlpatterns = [

        path('menu/', views.Menu.as_view(), name='menu'),
        path('changemenu/', views.changeMenu, name='changemenu'),
        path('menu/<int:id>/deletemenu', views.deleteMenu, name='deletemenu'),

        path('insertplate/', views.insertPlate, name='insertplate'),
        #path('insertplate/', views.InsertPlate.as_view(), name='insertplate'),
        path('listplate/', views.ListPlates.as_view(), name = 'listplate'),
        path('listplate/<int:id>/changeplate', views.changePlate, name='changeplate'),
        path('listplate/<int:id>/deleteplate', views.deletePlate, name='deleteplate'),
        path('listordini/',views.ListOrdini.as_view(), name='listordini'),

        path('ordine/',views.ordine,name='ordine'),
        path('ordine/<int:id>/deleteordine', views.deleteOrdine, name='deleteordine'),
        

        path('statistics/',views.StatisticsList.as_view(), name='statistics'),


]

mensa/mensa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
    path('',  TemplateView.as_view(template_name='app/home.html'), name='home'),

]

mensa/django-mensa/app/templates/app/changeMenu.html
{% extends 'accounts/base.html' %}

{% block title %}Change Menu{% endblock %}

{% block content %}

{% load static %}
<link href="{% static 'app/css/changeMenu.css' %}" rel="stylesheet">

  <div class="changemenu">
      <h1>Cambia il  menu</h1><br>
        <h3>In questa schermata puoi aggiungere un piatto al menu</h3><br>
        <form method="post" onsubmit="return checkform()">
            {% csrf_token %}
            {{ form.as_p }}
        <button type="submit">Inserisci</button>
      </form>
      <script type="text/javascript">

        function checkform() {
          alert("Piatto inserito correttamente nel Menu");
          return true;
        }

      </script>
</div>
{% endblock %}

mensa/django-mensa/app/templates/app/changePlate.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}Change Plate{% endblock %}

{% block content %}
<link href="{% static 'app/css/changePlate.css' %}" rel="stylesheet">

<h1>Aggiornamento Piatto </h1>
<br>
<h3>In questa schermata puoi modificare un piatto</h3>
<br>
<br>
<form method="post" onsubmit="return checkprice()" ><!--data-parsley-validate>-->
  {% csrf_token %}
  {{ form.as_p }}
<button type="submit">Aggiorna</button>
</form>


<script src="{% static '/accounts/js/jquery.min.js' %}"></script>
<script src="{% static 'app/js/changeplate.js'%}"></script>
<!--<script src="{% static '/accounts/js/parsley.min.js' %}"></script>-->


{% endblock %}

mensa/django-mensa/app/templates/app/home.html
<!-- templates/accounts/home.html -->
{% extends 'accounts/base.html' %}

{% block title %}Home{% endblock %}


{% block content %}
{% load static %}
<link href="{% static 'app/css/home.css' %}" rel="stylesheet">
    <!-- Header -->

        <div class="span12">
           <div class="col-md-6 no-gutter text-center fill">
             {% if user.is_authenticated %}
              <h1 class="vcenter">Benvenuto {{user.username}}</h1>
            {% else %}
                <h1 class="vcenter">Benvenuto</h1>
            {% endif %}
           </div>

           <div class="col-md-6 no-gutter text-center">
              <div id="header" data-speed="2" data-type="background">
                 <div id="headslide" class="carousel slide" data-ride="carousel">
                    <div class="carousel-inner" role="listbox">
                       <div class="item active">
                         <img src="{% static 'app/img/lasagna.jpg' %}" alt="Slide">
                       </div>
                       <div class="item">
                          <img src="{% static 'app/img/bistecca.jpg' %}" alt="Slide">
                       </div>
                       <div class="item">
                          <img src="{% static 'app/img/dolce.jpg' %}" alt="Slide">
                       </div>
                       <div class="item">
                          <img src="{% static 'app/img/wine.jpg' %}" alt="Slide">
                       </div>
                    </div>
                 </div>
              </div>
           </div>
        </div>
        <div style="clear:both;"></div>



<!--
{% if user.is_authenticated %}
  Hi {{ user.username }}!
  <p><a href="{% url 'logout' %}">logout</a></p>
  <p><a href="{% url 'password_reset' %}">reset password</a></p>
{% else %}
  <p>You are not logged in</p>
  <a href="{% url 'login' %}">login</a>
{% endif %}
-->
{% endblock %}

mensa/django-mensa/app/templates/app/insertPlate.html
{% extends 'accounts/base.html' %}
{% load static %}
{% block title %}Insert Plate{% endblock %}

{% block content %}
<link href="{% static 'app/css/insertplate.css' %}" rel="stylesheet">

<div class="insertplate">
<h1>Inserisci un piatto</h1>
<h3>In questa schermata puoi inserire un piatto nel database</h3>
<br>
<form method="post" onsubmit="return checkprice()"> <!-- data-parsley-validate> -->
  {% csrf_token %}
  {{ form.as_p }}
<button type="submit">Inserisci</button>
</form>

</div>


<script src="{% static '/accounts/js/jquery.min.js' %}"></script>
<script src="{% static 'app/js/insertplate.js' %}"></script>
<!--<script src="{% static '/accounts/js/parsley.min.js' %}"></script>
-->


{% endblock %}

mensa/django-mensa/app/templates/app/listPlates.html
{% extends 'accounts/base.html' %}

{% block title %}Lista Piatti{% endblock %}

{% block content %}
{% load static %}
<link href="{% static 'app/css/listplates.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

<h1>Lista Piatti</h1>
<br>
<h3>In questa schermata sono presenti tutti i piatti nel database</h3>

{% if list_plates|length != 0 %}
<h2> Primo</h2>
{% for plate in list_plates %}
  {% if plate.menu_name.name == 'Primo' %}
    <form method="post" >
      {% csrf_token %}
      <h3>{{plate.name}}
      <button class="btn" name="change" value="{{plate.pk}}"><i class="fa fa-edit"></i>Edit</button>
      <button class="btn" name="delete" value="{{plate.pk}}"><i class="fa fa-close"></i>Remove</button>
      <button class="btn" name="search" value="{{plate.name}}"><i class="fa fa-youtube-square" ></i><a href="https://www.youtube.com/results?search_query=ricetta+{{plate.name}}" target="_blank" id="youtube"> Search</a></button>
      </h3>
    </form>
  {%endif%}
{%endfor%}

  <h2>Secondo</h2>
  {% for plate in list_plates %}
  {%if plate.menu_name.name == 'Secondo' %}
    <form method="post">
      {% csrf_token %}
      <h3>{{plate.name}}
        <button class="btn" name="change" value="{{plate.pk}}"><i class="fa fa-edit"></i>Edit</button>
        <button class="btn" name="delete" value="{{plate.pk}}"><i class="fa fa-close"></i>Remove</button>
        <button class="btn" name="search" value="{{plate.name}}"><i class="fa fa-youtube-square"></i><a href="https://www.youtube.com/results?search_query=ricetta+{{plate.name}}" id="youtube" target="_blank"> Search</a></button>
      </h3>
    </form>
      {%endif%}
    {%endfor%}

    <h2>Contorno</h2>
    {% for plate in list_plates %}
    {% if plate.menu_name.name == 'Contorno' %}
      <form method="post">
        {% csrf_token %}
            <h3>{{plate.name}}
            <button class="btn" name="change" value="{{plate.pk}}"><i class="fa fa-edit"></i>Edit</button>
            <button class="btn" name="delete" value="{{plate.pk}}"><i class="fa fa-close"></i>Remove</button>
            <button class="btn" name="search" value="{{plate.name}}"><i class="fa fa-youtube-square"></i><a href="https://www.youtube.com/results?search_query=ricetta+{{plate.name}}" id="youtube" target="_blank"> Search</a></button>
        </h3>
      </form>
      {%endif%}
      {%endfor%}

      <h2>Dessert</h2>
      {% for plate in list_plates %}
      {% if plate.menu_name.name == 'Dessert' %}
      <form method="post">
          {% csrf_token %}
          <h3>{{plate.name}}
            <button class="btn" name="change" value="{{plate.pk}}"><i class="fa fa-edit"></i>Edit</button>
            <button class="btn" name="delete" value="{{plate.pk}}"><i class="fa fa-close"></i>Remove</button>
            <button class="btn" name="search" value="{{plate.name}}"><i class="fa fa-youtube-square"></i><a href="https://www.youtube.com/results?search_query=ricetta+{{plate.name}}" id="youtube" target="_blank"> Search</a></button>
          </h3>
        </form>
        {%endif%}
      {%endfor%}
{% else %}
  <h1>Nessun piatto nel Database  </h1>:
  <a href="{% url 'app:insertplate' %}"></a>
{%endif%}

{% endblock %}

mensa/django-mensa/app/templates/app/menu.html
{% extends 'accounts/base.html' %}

{% block title %}Menu{% endblock %}

{% block content %}

{% load static %}
  <link href="{% static 'app/css/menu.css' %}" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!-- Header -->

    <table>
    <tr>
      <th>
    <br>
      <h1>Menu</h1>

          {% if menu_dict.Primo|length == 0 and menu_dict.Secondo|length == 0 and menu_dict.Contorno|length == 0 and menu_dict.Dessert|length == 0 %}
               <h1>Il menu e' vuoto</h1>
             {% else %}
             {% if user.groups.all.0.name == 'Cuoco'  %}
             <h2>Primo</h2>
             {% for p in menu_dict.Primo %}
               <h3>{{p.name}}   {{p.price}} Euro</h3>
               <form action="" method="post" id="formPrimo">
                 {% csrf_token %}
                   <button class="btn" name="change"  form="formPrimo" value="{{p.pk}}" ><i class="fa fa-edit"></i>Edit</button>
                   <button class="btn" name="delete"  form="formPrimo" value="{{p.pk}}" ><i class="fa fa-close"></i>Remove</button>
               </form>
               <br>
               <br>
             {%endfor%}
             <h2>Secondo</h2>
             {% for p in menu_dict.Secondo %}
               <h3>{{p.name}}   {{p.price}} Euro</h3>
               <form action="" method="post" id="formSecondo">
                 {% csrf_token %}
                 <button class="btn" name="change"  form="formSecondo" value="{{p.pk}}" ><i class="fa fa-edit"></i>Edit</button>
                 <button class="btn" name="delete"  form="formSecondo" value="{{p.pk}}" ><i class="fa fa-close"></i>Remove</button>
                 </form>
               <br>
               <br>
             {%endfor%}
             <h2>Contorno</h2>
             {% for p in menu_dict.Contorno %}
               <h3>{{p.name}}   {{p.price}} Euro</h3>
               <form action="" method="post" id="formContorno">
                 {% csrf_token %}
                 <button class="btn" name="change"  form="formContorno" value="{{p.pk}}" ><i class="fa fa-edit"></i>Edit</button>
                 <button class="btn" name="delete"  form="formContorno" value="{{p.pk}}" ><i class="fa fa-close"></i>Remove</button>
                 </form>
               <br>
               <br>
             {%endfor%}
             <h2>Dessert</h2>
             {% for p in menu_dict.Dessert %}
               <h3>{{p.name}}   {{p.price}} Euro</h3>
               <form action="" method="post" id="formDessert">
                 {% csrf_token %}
                 <button class="btn" name="change"  form="formDessert" value="{{p.pk}}" ><i class="fa fa-edit"></i>Edit</button>
                 <button class="btn" name="delete"  form="formDessert" value="{{p.pk}}" ><i class="fa fa-close"></i>Remove</button>
                </form>
              <br>
              <br>
             {%endfor%}
             {%else%}
             <h2>Primo</h2>
             {% for p in menu_dict.Primo %}
               <h3>{{p.name}}   {{p.price}} Euro
               <button class="btn" name="search" value="{{p.name}}"><i class="fa fa-youtube-square" ></i><a href="https://www.youtube.com/results?search_query=ricetta+{{p.name}}" target="_blank" id="youtube"> Search</a></button>
               </h3>
               <br>
             {%endfor%}
             <h2>Secondo</h2>
             {% for p in menu_dict.Secondo %}
               <h3>{{p.name}}   {{p.price}} Euro
               <button class="btn" name="search" value="{{p.name}}"><i class="fa fa-youtube-square" ></i><a href="https://www.youtube.com/results?search_query=ricetta+{{p.name}}" target="_blank" id="youtube"> Search</a></button>
               </h3>
               <br>
             {%endfor%}
             <h2>Contorno</h2>
             {% for p in menu_dict.Contorno %}
               <h3>{{p.name}}   {{p.price}} Euro
               <button class="btn" name="search" value="{{p.name}}"><i class="fa fa-youtube-square" ></i><a href="https://www.youtube.com/results?search_query=ricetta+{{p.name}}" target="_blank" id="youtube"> Search</a></button>
               </h3>
               <br>
             {%endfor%}
             <h2>Dessert</h2>
             {% for p in menu_dict.Dessert %}
             <h3>{{p.name}}   {{p.price}} Euro
               <button class="btn" name="search" value="{{p.name}}"><i class="fa fa-youtube-square" ></i><a href="https://www.youtube.com/results?search_query=ricetta+{{p.name}}" target="_blank" id="youtube"> Search</a></button>
            </h3>
               <br>
             {%endfor%}
             {%endif%}
             {%endif%}

        </th>
        </tr>
        </table>
{% endblock %}

mensa/django-mensa/app/templates/app/ordine.html
{% extends 'accounts/base.html' %}

{% block title %}Ordina{% endblock %}

{% block content %}

{% load static %}
<link href="{% static 'app/css/ordine.css' %}" rel="stylesheet">
<script src="{% static '/app/js/ordine.js' %}"></script>


<h1>Ordina</h1>

<form method="post">
  {% csrf_token %}

  <!-- Bisogna far vedere anche il prezzo -->
  <h3>Scegli un piatto:</h3>
  <br>
  {% for plate in form.fields.plate_chosen.queryset%}
  <label for={{plate.id}}>
    <div class='container'>
      <div class='key-div'>
        {{plate.name}}
      </div>
      <div class='value-div'>
        <label id ={{plate.id}}label> {{plate.price}} </label> €
        <input type="checkbox" name="plate_chosen" value={{plate.id}} id={{plate.id}} onclick="countTotal()">
      </div>
    </div>
  </label>
  {%endfor%}
<br>
<br>
<strong>Data Prenotazione:</strong>   {{ form.date }}

<br>
<br>
  <strong>Totale: <span id="total">0</span> € </strong>
<br>
<br>


<button type="submit">ordina</button>
</form>



{% endblock %}

mensa/django-mensa/app/templates/app/ordine_cuoco.html
{% extends 'accounts/base.html' %}

{% block title %}Ordina{% endblock %}

{% block content %}

{% load static %}
<link href="{% static 'app/css/ordine_cuoco.css' %}" rel="stylesheet">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


<h1>Lista ordini</h1>


{% if user.is_authenticated and user.groups.all.0.name == 'Cuoco' or user.username == 'admin' %}

{% for day,ordine in list_ordini.items%}

{% if ordine.0|length != 0%}
<h2>{{day}}</h2>

<table>
  <tr>
  <th>ID</th>
  <th>Nome</th>
  <th>Lista Piatti</th>
  </tr>
  {% for o in ordine.0 %}
  <tr>
    <td>{{o.id}}</td>
    <td>{{o.name}}</td>
    {% for plate in o.plate_chosen.all %}
      <td>{{plate.name}}</td>
      {%endfor%}
  </tr>
  {%endfor%}
</table>
{%endif%}
{%endfor%}
{% endif %}
<!------------------------------------------------------------------------->

{% if user.is_authenticated and user.groups.all.0.name == 'Impiegato' %}

{% for day,ordine in list_ordini.items%}

<h2>{{day}}</h2>
<table>
  <tr>
  <th>ID</th>
  <th>Nome</th>
  <th>Lista Piatti</th>

  </tr>

  {% for o in ordine.0 %}
  {% if o.name == user.username %}
  <tr>
    <td>{{o.id}}</td>
    <td>{{o.name}}</td>

    {% for plate in o.plate_chosen.all %}
      <td>{{plate.name}}</td>
    {%endfor%}
    <td><b>Totale Ordine</b> : {{o.total}} Euro</td>
    <td>
      <form action="{% url 'app:deleteordine' o.id %}" method="post">
        {% csrf_token %}
      <button class="btn" name="delete"><i class="fa fa-close"></i>Remove</button>
      </form>
    </td>

  </tr>
  {% endif %}
  {%endfor%}
</table>

{%endfor%}
{% endif %}



{% endblock %}

mensa/django-mensa/app/templates/app/statistiche.html
{% extends 'accounts/base.html' %}

{% block title %}Statistiche{% endblock %}

{% block content %}
{% load static %}
<link href="{% static 'app/css/statistiche.css' %}" rel="stylesheet">

<h1>Statistiche</h1>
<br><br>

<!-- First Container -->

<div class="container-fluid bg-1 text-center">
    <h3 class="margin2">Costo per dipendente</h3>
<table>
<tr>
  <th>User</th>
  {% for d in day %}
  <th>{{d}}</th>
  {%endfor%}
  <th id="weekly_title">Totale Settimanale</th>
</tr>
{% for key,value in daily_cost.items %}
<tr>
  <td>{{key}}</td>
  {%for v in value%}
  <td>{{v}} €</td>
  {%endfor%}
</tr>
{%endfor%}
</table>
</div>





<!-- Second Container -->
<div class="container-fluid bg-2 text-center">
  <h3 class="margin2">Scelte per piatto </h3>
<table>
<tr>
  <th>Plate</th>
  {% for d in day %}
  <th>{{d}}</th>
  {%endfor%}
  <th >Totale Settimanale</th>
</tr>
{% for key,value in daily_chose.items %}
<tr>
  <td>{{key}}</td>
  {%for v in value%}
  <td>{{v}}</td>
  {%endfor%}
</tr>
{%endfor%}

</table>
</div>


{% endblock %}


{%block content2%}


<!-- Third Container -->
<div class="container-fluid bg-3 text-center">
<dl>
  <dt>
    <h3 class="margin">Scelta per piatto (Grafico %)</h3>
  </dt>
    {% for key,value in total_chose.items %}

    <dd class="percentage percentage-{{value.1|stringformat:"d"}}"><span class="text">{{key}}: {{value.1}}%</span></dd>

    {%endfor%}

</dl>
</div>

<div class="container-fluid bg-3 text-center">
<dl>
  <dt>
    <h3 class="margin">
      Costo per dipendente (Grafico %)
      </h3>
  </dt>
    {% for key,value in total_cost.items %}

    <dd class="percentage percentage-{{value.1|stringformat:"d"}}">
      <span class="text">{{key}}:{{value.1}}% </span></dd>

    {%endfor%}

</dl>

</div>



<!-- Forth Container-->
<div class="container-fluid bg-4 text-center">
  <h3 class="margin2">Top 3 dei piatti scelti</h3>

  <h3 class="margin2">1.  {{top_3.0.0}} {{top_3.0.1.1}}%</h3><br>
  <h3 class="margin2">2.  {{top_3.1.0}} {{top_3.1.1.1}}%</h3><br>
  <h3 class="margin2">3.  {{top_3.2.0}} {{top_3.2.1.1}}%</h3>


</div>




{%endblock%}