mensa/django-mensa/accounts/urls.py
# accounts/urls.py
from django.urls import path, include
from . import views


app_name = 'accounts'

urlpatterns = [
        path('signup/', views.SignUp.as_view(), name='signup'),

]

mensa/django-mensa/app/urls.py
# app/urls.py
from django.urls import path, include
from . import views


app_name = 'app'

urlpatterns = [

        path('menu/', views.Menu.as_view(), name='menu'),
        path('changemenu/', views.changeMenu, name='changemenu'),
        path('menu/<int:id>/deletemenu', views.deleteMenu, name='deletemenu'),

        path('insertplate/', views.insertPlate, name='insertplate'),
        #path('insertplate/', views.InsertPlate.as_view(), name='insertplate'),
        path('listplate/', views.ListPlates.as_view(), name = 'listplate'),
        path('listplate/<int:id>/changeplate', views.changePlate, name='changeplate'),
        path('listplate/<int:id>/deleteplate', views.deletePlate, name='deleteplate'),
        path('listordini/',views.ListOrdini.as_view(), name='listordini'),

        path('ordine/',views.ordine,name='ordine'),
        path('ordine/<int:id>/deleteordine', views.deleteOrdine, name='deleteordine'),
        

        path('statistics/',views.StatisticsList.as_view(), name='statistics'),


]

mensa/mensa/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView


urlpatterns = [
    path('accounts/', include('accounts.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('app/', include('app.urls')),
    path('admin/', admin.site.urls),
    path('',  TemplateView.as_view(template_name='app/home.html'), name='home'),

]

mensa/django-mensa/accounts/models.py
from django.db import models

# Create your models here.

mensa/django-mensa/accounts/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User, Group
from .form import RegisterForm
from django.urls import reverse_lazy
from django.views import generic

# Create your views here.
class SignUp(generic.CreateView):
    """View Sign up che gestisce la funzione di registrazione
    di un nuovo utente. """
    form_class = RegisterForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'


    def post(self, request, *args, **kwargs):
        """Funzione post che raccoglie i dati inseriti dal nuovo user.
           In caso di successo:
                    --> porta l'user alla pagina di login
           In caso di fallimento:
                    --> genera un errore e fa riprovare l'inserimento """
        if request.method == 'POST':
            form = RegisterForm(request.POST)
            if form.is_valid():
                user = form.save()
                group = Group.objects.get(name=user.group)
                user.groups.add(group)
                return redirect('login')
            else:
                form = RegisterForm()
        return render(request, 'accounts/signup.html', {'form': form})

mensa/django-mensa/accounts/templates/accounts/base.html
<!-- templates/accounts/base.html -->
{% load static %}
<!DOCTYPE html>
<html>
<head>

  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <link href="{% static 'app/css/bootstrap.css' %}" rel="stylesheet">
  <link href="{% static 'app/css/style.css' %}" rel="stylesheet">

  <title>{% block title %}Django Auth Title{% endblock %}</title>


</head>


<body>
  <nav class="navbar navbar-default navbar-fixed-top">
             <div class="col-md-12">
                <div class="nav">
                   <button class="btn-nav">
                   <span class="icon-bar inverted top"></span>
                   <span class="icon-bar inverted middle"></span>
                   <span class="icon-bar inverted bottom"></span>
                   </button>
                </div>
                <div class="nav-content hideNav hidden">
                   <ul class="nav-list vcenter">
                      <li class="nav-item"><a class="item-anchor" href="{% url 'home' %}">Home</a></li>
                        <li class="nav-item"><a class="item-anchor" href="{% url 'app:menu' %}">Menu</a></li>
                      {% if user.is_authenticated %}
                      <!-- user02_ -->
                      {% if user.groups.all.0.name == 'Impiegato' or user.username == 'admin' %}
                        <li class="nav-item"><a class="item-anchor" href="{% url 'app:ordine' %}">Ordina!</a></li>
                      {% endif%}
                      {% if user.groups.all.0.name == 'Impiegato' or user.username == 'admin' or  user.groups.all.0.name == 'Cuoco' %}
                        <li class="nav-item"><a class="item-anchor" href="{% url 'app:listordini' %}">Lista ordini</a></li>
                      {%endif%}

                      <!-- user01_ -->
                      {% if user.groups.all.0.name == 'Cuoco' or user.username == 'admin' %}
                        <li class="nav-item"><a class="item-anchor"  href="{% url 'app:changemenu' %}">Modifica il Menu</a></li>
                        <li class="nav-item"><a class="item-anchor"  href="{% url 'app:insertplate' %}">Inserisci nuovi piatti</a></li>
                        <li class="nav-item"><a class="item-anchor"  href="{% url 'app:listplate' %}">Lista dei piatti</a></li>
                      {% endif%}

                      {% if user.groups.all.0.name == 'Azienda' or user.username == 'admin' %}
                          <li class="nav-item"><a class="item-anchor" href="{% url 'app:statistics' %}">Statistiche</a></li>
                      {% endif%}

                        <li class="nav-item"><a class="item-anchor" href="{% url 'password_reset' %}">Reset password</a></li>
                        <li class="nav-item"><a class="item-anchor" href="{% url 'logout' %}">Logout</a></li>
                    {% else %}

                      <li class="nav-item"><a class="item-anchor" href="{% url 'login' %}">Login</a></li>
                      <li class="nav-item"><a class="item-anchor" href="{% url  'accounts:signup' %}">Sign Up</a></li>
                    {% endif%}

                   </ul>
                </div>
             </div>
  </nav>



<main>
  <center>
    {% block content %}
    {% endblock %}
  </center>

  {%block content2%}

  {%endblock%}


</main>


<!-- script -->
<script src="{% static '/app/js/jquery.js' %}"></script>
<script src="{% static '/app/js/bootstrap.min.js' %}"></script>
<script src="{% static '/app/js/menu-color.js' %}"></script>
<script src="{% static '/app/js/script.js' %}"></script>


</body>


<footer>
</footer>




</html>

mensa/django-mensa/accounts/templates/accounts/signup.html
{% extends './base.html' %}

{% block title %}Signup{% endblock %}


{% load static %}


{% block content %}

<link href="{% static 'accounts/css/signup.css' %}" rel="stylesheet">
<script src="{% static '/accounts/js/jquery.min.js' %}"></script>
<!--<script src="{% static '/accounts/js/parsley.min.js' %}"></script>
-->
<div>
  <p style="float: right;">
     <img src="{% static 'accounts/img/signup.svg' %}">
  </p>

<div class="signup">
  <h2>Sign up</h2>
  <br>


  <form method="post" onsubmit="return checkpassword()"> <!--data-parsley-validate>-->
    {% csrf_token %}
  <!--  {{form.as_p}} -->
    {{ form.username.label_tag }} {{ form.username }}<br><br>
    {{ form.password1.label_tag}} {{ form.password1 }}
     <span id="characters"></span><br>
     <!--<span class="helptext" id="helptext"></span>-->
     <br>
    {{ form.password2.label_tag }} {{ form.password2 }}
    <span id="characters2"></span><br><br>
    {{ form.email.label_tag }} {{ form.email }}<br><br>
    {{ form.group.label_tag }} {{ form.group }}<br><br>

    <button type="submit">Sign up</button>
  </form>
</div>

</div>


<script src="{% static '/accounts/js/signup.js' %}"></script>




{% endblock %}